MVC_Web/BirdMealOrderSystem/RazorPage/Pages/Customer/CustomerCart.cshtml.cs
using BussinessObject;
using DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Protocols;
using Repository;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;

namespace RazorPage.Pages.Customer
{
    public class CustomerCartModel : PageModel
    {
        IComboRepository comboRepository = new ComboRepository();
        IComboDetailRepository comboDetailRepository = new ComboDetailRepository();
        IProductRepository productRepository = new ProductRepository();
        IOrderRepository orderRepository = new OrderRepository();
        IOrderComboDetailRepository orderComboDetailRepository = new OrderComboDetailRepository();
        IOrderProductDetailRepository orderProductDetailRepository = new OrderProductDetailRepository();
        IUserRepository userRepository = new UserRepository();
        public List<ShoppingItem> cart { get; set; }
        public decimal Total { get; set; }
        [Required(ErrorMessage = "ship address is required!")]
        [StringLength(200, MinimumLength = 1, ErrorMessage = "The length of ship address is from 1 to 200 charater")]
        public string Shippaddress { get; set; }

        public string Message { get; set; }

        public IActionResult OnGet()
        {
            if (!SessionHelper.checkPermission(HttpContext.Session, "customer"))
            {
                return Redirect("~/Index");
            }
            List<string> listStatus = new List<string>();
            listStatus.Add("VNPay");
            listStatus.Add("Payment on delivery");
            ViewData["payment"] = new SelectList(listStatus);
            cart = SessionHelper.GetObjectFromJson<List<ShoppingItem>>(HttpContext.Session, "cart");
            if (cart != null && cart.Count > 0)
                Total = (decimal)cart.Sum(i => ((double)i.unitPirce) * i.quantity - ((double)i.unitPirce) * i.quantity * (i.discount / 100));
            return Page();
        }

        public IActionResult OnGetBuyNow(int id, string type)
        {
            if (!SessionHelper.checkPermission(HttpContext.Session, "customer"))
            {
                return Redirect("~/Index");
            }
            List<string> listStatus = new List<string>();
            listStatus.Add("VNPay");
            listStatus.Add("Payment on delivery");
            ViewData["payment"] = new SelectList(listStatus);
            cart = SessionHelper.GetObjectFromJson<List<ShoppingItem>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<ShoppingItem>();
                if (type.Equals("combo"))
                {
                    Combo combo = comboRepository.GetById(id);
                    cart.Add(new ShoppingItem
                    {
                        type = "combo",
                        ItemId = id,
                        discount = combo.Discount,
                        quantity = 1,
                        unitPirce = combo.Price,
                        imgLink = "",
                        name ="Combo " + combo.ComboName
                    });
                }

                if (type.Equals("product"))
                {
                    Product product = productRepository.GetById(id);
                    cart.Add(new ShoppingItem
                    {
                        type = "product",
                        ItemId = id,
                        discount = product.ProductDiscount,
                        quantity = 1,
                        unitPirce = product.UnitPrice,
                        imgLink = product.ImageLink,
                        name = product.ProductName
                    });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = Exists(cart, id, type);
                if (index == -1)
                {

                    if (type.Equals("product"))
                    {
                        Product product = productRepository.GetById(id);
                        cart.Add(new ShoppingItem
                        {
                            type = "product",
                            ItemId = id,
                            discount = product.ProductDiscount,
                            quantity = 1,
                            unitPirce = product.UnitPrice,
                            imgLink = product.ImageLink,
                            name = product.ProductName
                        });
                    }
                    if (type.Equals("combo"))
                    {
                        Combo combo = comboRepository.GetById(id);
                        cart.Add(new ShoppingItem
                        {
                            type = "combo",
                            ItemId = id,
                            discount = combo.Discount,
                            quantity = 1,
                            unitPirce = combo.Price,
                            imgLink = "",
                            name ="Combo " + combo.ComboName
                        });
                    }

                }
                else
                {
                    cart[index].quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("CustomerCart");
        }
        public IActionResult OnGetDelete(int id, string type)
        {
            if (!SessionHelper.checkPermission(HttpContext.Session, "customer"))
            {
                return Redirect("~/Index");
            }
            List<string> listStatus = new List<string>();
            listStatus.Add("VNPay");
            listStatus.Add("Payment on delivery");
            ViewData["payment"] = new SelectList(listStatus);
            cart = SessionHelper.GetObjectFromJson<List<ShoppingItem>>(HttpContext.Session, "cart");
            int index = Exists(cart, id, type);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("CustomerCart");
        }

        public IActionResult OnPostUpdate(int[] quantities)
        {
            if (!SessionHelper.checkPermission(HttpContext.Session, "customer"))
            {
                return Redirect("~/Index");
            }
            List<string> listStatus = new List<string>();
            listStatus.Add("VNPay");
            listStatus.Add("Payment on delivery");
            ViewData["payment"] = new SelectList(listStatus);
            cart = SessionHelper.GetObjectFromJson<List<ShoppingItem>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].quantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("CustomerCart");
        }
        public IActionResult OnPostSubmit(string shippaddress, string paymentMethod)
        {
            Shippaddress = shippaddress;
            string s = paymentMethod;
            cart = SessionHelper.GetObjectFromJson<List<ShoppingItem>>(HttpContext.Session, "cart");
            if (cart != null && cart.Count > 0)
                Total = (decimal)cart.Sum(i => ((double)i.unitPirce) * i.quantity - ((double)i.unitPirce) * i.quantity * (i.discount / 100));
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            if (!SessionHelper.checkPermission(HttpContext.Session, "customer"))
            {
                return Redirect("~/Index");
            }
            List<string> listStatus = new List<string>();
            listStatus.Add("VNPay");
            listStatus.Add("Payment on delivery");
            ViewData["payment"] = new SelectList(listStatus);
            cart = SessionHelper.GetObjectFromJson<List<ShoppingItem>>(HttpContext.Session, "cart");
            if (!ModelState.IsValid)
            {
                cart = SessionHelper.GetObjectFromJson<List<ShoppingItem>>(HttpContext.Session, "cart");
                if (cart != null && cart.Count > 0)
                    Total = (decimal)cart.Sum(i => ((double)i.unitPirce) * i.quantity - ((double)i.unitPirce) * i.quantity * (i.discount / 100));
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                return Page();
            }

            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].type.Equals("combo"))
                {
                    Combo combo = comboRepository.GetById((int)cart[i].ItemId);
                    foreach (ComboDetail cbd in combo.ComboDetails)
                    {
                        Product product = productRepository.GetById((int)cbd.ProductId);
                        ShoppingItem tmp = cart.Where(item => item.type.Equals("product") && item.ItemId == cbd.ProductId).ToList().SingleOrDefault();
                        int quantityTmp = 0;
                        if (tmp != null)
                        {
                            quantityTmp = tmp.quantity;
                        }
                        if (product.UnitInStock < (cart[i].quantity*cbd.Quantity + quantityTmp))
                        {
                            Message = combo.ComboName + " is not enough quantity to buy!\n";
                            cart = SessionHelper.GetObjectFromJson<List<ShoppingItem>>(HttpContext.Session, "cart");
                            if (cart != null && cart.Count > 0)
                                Total = (decimal)cart.Sum(i => ((double)i.unitPirce) * i.quantity - ((double)i.unitPirce) * i.quantity * (i.discount / 100));

MVC_Web/BirdMealOrderSystem/RazorPage/Pages/Customer/MyOrder.cshtml.cs
using BussinessObject;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System;
using System.Linq;

namespace RazorPage.Pages.Customer
{
    public class MyOrderModel : PageModel
    {
        IOrderRepository orderRepository = new OrderRepository();
        public int numberOfOrder { get; set; }
        public decimal Total { get; set; }
        public string Message { get; set; }

        [Required]
        [BindProperty]
        public DateTime orderStart { get; set; }

        [Required]
        [BindProperty]
        public DateTime orderEnd { get; set; }



        public IList<Order> Order { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            if (!SessionHelper.checkPermission(HttpContext.Session, "customer"))
            {
                return Redirect("~/ErrorRole");
            }
            Order = orderRepository.GetAll().Where(o => o.UserId == SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "cusId")).ToList();
            numberOfOrder = Order.Count();
            Total = (decimal)Order.Sum(od => od.Total);
            orderStart = DateTime.Now.AddDays(-7);
            orderEnd = DateTime.Now;
            return Page();
        }

        public IActionResult OnPostGenerate()
        {
            if (!SessionHelper.checkPermission(HttpContext.Session, "customer"))
            {
                return Redirect("~/ErrorRole");
            }
            if (orderEnd <= orderStart)
            {
                Message = "Start date must less than end date!";
                return Page();
            }

            Order = (from o in orderRepository.GetAll().Where(o => o.UserId == SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "cusId")).ToList()
                     where o.OrdeDate <= orderEnd && o.OrdeDate >= orderStart
                     orderby o.Total descending
                     select o
                     ).ToList();
            numberOfOrder = Order.Count();
            Total = (decimal)Order.Sum(od => od.Total);
            return Page();
        }
    }
}

MVC_Web/BirdMealOrderSystem/RazorPage/Pages/Customer/CustomerCart.cshtml
@page
@model RazorPage.Pages.Customer.CustomerCartModel
@{
    Layout = "LayoutCustomer";
}

<div class="d-flex justify-content-between">
    <a asp-page="/ShoppingProduct">
        <img src="~/images/back-icon-3.png" style="padding-left: 30px;" />
    </a>
    <div>
    </div>
    <div>
    </div>
</div>
<div class="d-flex justify-content-center">
    <span class="mx-2 span-custom"><a style="font-weight: 500; color: #5A5A5A; text-decoration: none;" asp-page="Index">Home</a></span>
    <span> / </span>
    <span class="mx-2" style="font-weight: 500; color: #000;">My Cart</span>
</div>
<h1 class="text-center mt-5 mb-5">MY CART</h1>

<hr />

@if (Model.cart != null && Model.cart.Count > 0)
{
    <div class="container">
        <h3 style="margin-bottom: 30px;">COMBO</h3>
        <form method="post" asp-page="customerCart" asp-page-handler="update">
            <table class="table">
                <thead class="table-dark">
                    <tr>
                        <th class="text-center"></th>
                        <th class="text-center">Product name</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Quantity</th>
                        <th class="text-center">Discount(%)</th>
                        <th class="text-center">Sub total</th>
                        <th class="text-center">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.cart)
                    {
                        String imgLink = item.imgLink;
                        <tr align="center">
                            <td style="padding-top: 15px;">
                                @{
                                    if (imgLink != null)
                                    {
                                        <img src="~/uploads/@imgLink" width="100px" height="100px" />
                                    }
                                    else
                                    {
                                        <img src="~/images/combo.png" width="100px" height="100px" />
                                    }
                                }

                            </td>
                            <td style="padding-top: 15px;">@item.name</td>
                            <td style="padding-top: 15px;">@item.unitPirce</td>
                            <td style="padding-top: 15px;"><input type="number" name="quantities" value="@item.quantity" min="1" style="width: 50px;" /></td>
                            <td style="padding-top: 15px;">@item.discount</td>
                            <td style="padding-top: 15px;">
                                @((double)item.unitPirce * item.quantity - (double)(item.unitPirce * item.quantity) * item.discount / 100) vnđ
                            </td>
                            <td style="padding-top: 15px;">
                                <button class="btn-danger rounded-pill px-4 py-2"><a asp-page="customerCart" asp-page-handler="delete" asp-route-id="@item.ItemId" asp-route-type="@item.type" style="color: #fff; text-decoration: none; font-weight: 600;">X</a></button>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6" align="right" style="font-weight: 500; font-size: 20px;">Total</td>
                        <td align="center">@(Model.Total) vnđ</td>
                    </tr>
                </tfoot>
            </table>
            <div class="d-flex justify-content-end">
                <input class="btn btn-dark" type="submit" value="Update" />
            </div>

        </form>
        <form method="post" asp-page="customerCart" asp-page-handler="submit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Ship address</label>
                <input type="text" asp-for="@Model.Shippaddress" name="shippaddress" class="input-new" />
                <span asp-validation-for="@Model.Shippaddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Payment method</label>
                <select name="paymentMethod" class="form-control" asp-items="ViewBag.payment"></select>
            </div>
            <div>
                <p class="text-danger">@Model.Message</p>
            </div>
            <div class="form-group">
                <div class="d-flex justify-content-center">
                    <input type="submit" class="btn rounded-pill btn-primary px-4 py-2" />
                </div>

            </div>
        </form>
        <button class="btn-secondary rounded-pill px-4 py-2"><a href="~/ShoppingProduct" style="color: #fff; text-decoration: none; font-weight: 600;">Add Product</a></button>
        <button class="btn-secondary rounded-pill px-4 py-2"><a href="~/ShoppingCombo" style="color: #fff; text-decoration: none; font-weight: 600;">Add Combo</a></button>
    </div>
}
else
{
    <div class="card shadow p-3 mb-5 bg-white rounded" style="margin: 0 200px 0 200px;">
        <div class="" style="padding: 30px 30px 30px 30px;">
            <h4 class="card-header">
                Cart is empty
            </h4>
            <div class="d-flex justify-content-around" style="margin-top: 50px;">
                <button class="btn-primary rounded-pill px-4 py-2"><a href="~/ShoppingProduct" style="color: #fff; text-decoration: none; font-weight: 600;">Add Product</a></button>
                <button class="btn-primary rounded-pill px-4 py-2"><a href="~/ShoppingCombo" style="color: #fff; text-decoration: none; font-weight: 600;">Add Combo</a></button>
            </div>
        </div>
    </div>
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC_Web/BirdMealOrderSystem/RazorPage/Pages/Customer/MyOrder.cshtml
@page
@model RazorPage.Pages.Customer.MyOrderModel
@{
    Layout = "LayoutCustomer";
}

<div class="d-flex justify-content-between">
    <a asp-page="/ShoppingProduct">
        <img src="~/images/back-icon-3.png" style="padding-left: 30px;" />
    </a>
    <div>
    </div>
    <div>
    </div>
</div>
<div class="d-flex justify-content-center">
    <span class="mx-2 span-custom"><a style="font-weight: 500; color: #5A5A5A; text-decoration: none;" asp-page="/ShoppingProduct">Shopping Mall</a></span>
    <span> / </span>
    <span class="mx-2" style="font-weight: 500; color: #000;">My Orders</span>
</div>
<h1 class="text-center mt-5 mb-5">MY ORDERS</h1>

<hr />

<div class="card shadow p-3 mb-5 bg-white rounded" style="margin: 0 200px 0 200px;">
    <h1 class="text-center">Report</h1>

    <form method="post" asp-page-handler="generate">
        <div class="form-group">
            <label class="control-label">Order date from</label>
            <input asp-for="orderStart" class="form-control" />
            <span asp-validation-for="orderStart" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="control-label">To</label>
            <input asp-for="orderEnd" class="form-control" />
            <span asp-validation-for="orderStart" class="text-danger"></span>
        </div>
        <div class="">
            <label>Number of order:</label>
            <h4>@Model.numberOfOrder</h4>
            <lable>Total:</lable>
            <h4>@Model.Total</h4>

        </div>
        <div class="d-flex justify-content-center">
            <button class="btn-outline-primary" type="submit">Generate</button>
        </div>

        <div><span class="text-danger">@Model.Message</span></div>
    </form>
</div>
<table class="table">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].OrderStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].OrdeDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].ShippedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].ShipAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].Paymentmethod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].PaymentStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    @if (Model.Order != null)
    {
        <tbody>
            @foreach (var item in Model.Order)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Total)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderStatus)
                    </td>
                    <td>
                        @{
                            DateTime orderDate = (DateTime)item.OrdeDate;
                            string formatDate = orderDate.ToString("dd/MM/yyyy");
                        }
                        <span>@formatDate</span>
                    </td>
                    <td>
                        @Html.DisplayNameFor(model => model.Order[0].ShippedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Paymentmethod)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PaymentStatus)
                    </td>
                    <td>
                        <a asp-page="./MyOrderDetail" asp-route-id="@item.OrderId">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    }

</table>

MVC_Web/BirdMealOrderSystem/RazorPage/Pages/Customer/MyOrderDetail.cshtml
@page
@model RazorPage.Pages.Customer.MyOrderDetailModel
@{
    Layout = "LayoutCustomer";
}


<div class="d-flex justify-content-between">
    <a asp-page="./MyOrder">
        <img src="~/images/back-icon-3.png" style="padding-left: 30px;" />
    </a>
    <div>
    </div>
    <div>
    </div>
</div>
<div class="d-flex justify-content-center">
    <span class="mx-2" style="font-weight: 500; color: #000;">Details</span>
</div>
<h1 class="text-center mt-5 mb-5">ORDER DETAILS</h1>

<div class="card shadow p-3 mb-5 bg-white rounded" style="margin: 0 200px 0 200px;">
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Total)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.OrderStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.OrderStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.OrdeDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.OrdeDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.ShippedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.ShippedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.ShipAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.ShipAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Paymentmethod)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Paymentmethod)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.PaymentStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.PaymentStatus)
        </dd>
    </dl>
    <div class="d-flex justify-content-center">
        <span class="text-danger">@Model.Message</span>
        <div class="d-flex justify-content-center" style="margin-top: 15px;">
            <button class="btn-danger rounded-pill px-4 py-2"><a asp-page="myOrderDetail" asp-page-handler="delete" asp-route-id="@Model.Order.OrderId" style="color: #fff; text-decoration: none; font-weight: 600;">CANCEL</a></button>
        </div>
    </div>
</div>

<div class="card shadow p-3 mb-5 bg-white rounded" style="margin: 0 200px 0 200px;">
    <h4 class="text-center" style="font-weight: 500;">Rating</h4>
    <hr />

    @if (Model.orderComboDetails != null && Model.orderComboDetails.Count > 0)
    {
        <div>
            @foreach (var item in Model.orderComboDetails)
            {
                <div>
                    <h5>Combo @item.Combo.ComboName</h5>
                    <p><span style="font-weight: 500">Quantity: </span>@item.Quantity</p>
                    <p><span style="font-weight: 500">Unit price after discounted: </span>@(((double)item.UnitPrice) - ((double)item.UnitPrice * item.Discount / 100))</p>
                </div>
                if (item.Feedback == null || item.Feedback.Equals("notfeedback"))
                {
                    <form method="post" asp-page="myOrderDetail" asp-page-handler="commentCombo">
                        <input type="hidden" name="Orderid" value="@Model.Order.OrderId" />
                        <input type="hidden" name="id" value="@item.ComboId" />
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="">Comment</span>
                            </div>
                            <input name="commment" type="text" class="form-control">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Rating</span>
                                <span class="input-group-text">Star</span>
                            </div>
                            <input min="1" max="100" type="number" name="rating" class="form-control" aria-label="Amount">
                        </div>
                        <div class="d-flex justify-content-center">
                            <div class="form-group">
                                <input type="submit" class="btn btn-dark" />
                            </div>
                        </div>

                    </form>
                }
            }
        </div>
    }
    <hr />
    @if (Model.orderProductDetails != null && Model.orderProductDetails.Count > 0)
    {
        <div>
            @foreach (var item in Model.orderProductDetails)
            {
                <div>
                    <h5>Product @item.Product.ProductName</h5>
                    <p><span style="font-weight: 500">Quantity: </span>@item.Quantity</p>
                    <p><span style="font-weight: 500">Unit price after discounted: </span>@(((double)item.UnitPrice) - ((double)item.UnitPrice * item.Discount / 100))</p>
                </div>

                if (item.Feedback == null || item.Feedback.Equals("notfeedback"))
                {
                    <form method="post" asp-page="myOrderDetail" asp-page-handler="commentProduct">
                        <input type="hidden" name="Orderid" value="@Model.Order.OrderId" />
                        <input type="hidden" name="id" value="@item.ProductId" />
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="">Comment</span>
                            </div>
                            <input name="commment" type="text" class="form-control">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Rating</span>
                                <span class="input-group-text">Star</span>
                            </div>
                            <input min="1" max="100" type="number" name="rating" class="form-control" aria-label="Amount">
                        </div>
                        <div class="d-flex justify-content-center">
                            <div class="form-group">
                                <input type="submit" class="btn btn-dark" />
                            </div>
                        </div>

                    </form>
                }
            }
        </div>
    }
</div>